apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: webmis-deployment 
spec: 
  selector: 
    matchLabels: 
      app: webmis 
  replicas: 2 
  template:
    metadata: 
      labels: 
        app: webmis 
    spec: 
      containers: 
      - name: webmis 
        image: bineet/webmis:#{Build.BuildId}#
        ports: 
        - containerPort: 5555 
--- 
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  name: webmis-service 
spec: 
  selector: 
    app: webmis 
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 5555 
  type: LoadBalancer
