apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: microservice-deployment 
spec: 
  selector: 
    matchLabels: 
      app: microservice 
  replicas: 2 
  template:
    metadata: 
      labels: 
        app: microservice 
    spec: 
      containers: 
      - name: microservice 
        image: bineet/microservice:#{Build.BuildId}#
        ports: 
        - containerPort: 5555 
--- 
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  name: microservice-service 
spec: 
  selector: 
    app: microservice 
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 5555 
  type: LoadBalancer
